##############################################################################
## THREADING
##############################################################################

texdir: "/usr/bin"

# ----------------------------------------------------------------------------
# Number of threads to use for large, medium, and small multithreaded jobs;
#       if number passed to job is larger than number passed to whole
#       workflow, latter will be used instead.
# ----------------------------------------------------------------------------

threads:
    max: 18 # Max threads for large jobs
    med: 9 # Threads for medium jobs
    min: 4 # Min threads for small (but still multithreaded) jobs
