##############################################################################
## THREADING
##############################################################################

threads:
    max: 18 # Max threads for large jobs
    med: 9 # Threads for medium jobs
    min: 4 # Min threads for small (but still multithreaded) jobs

env_path: "env.yaml" # Path to Conda environment

rdi_path: "input_files/rdi_1.0.0.tar.gz" # Path to RDI package files
